name: Maven build shopfront

on:
  push:
    branches:
      - master
    paths:
      - shopfront/**
  pull_request:
    branches:
      - master
    paths:
      - shopfront/**
  workflow_dispatch:

jobs:
  build_image:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: mmmm
      id: "mmm"
      run: |
        echo \"packages=\"$(docker \
         version | grep version) >> $GITHUB_OUTPUT
    - name: m123
      run: >-
        echo "Output [${{steps.mmm.outputs.packages}}]"

    - name: Build project with Maven
      run: mvn -B package --file shopfront/pom.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker version
      run: docker version
        #- name: Set env
        #run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
    - name: Test
      run: echo $DOCKER_BUILDKIT
    - name: TEST DOCKER
      run: cd shopfront/ &&  docker buildx build -t frontend:0.1.1-dev.1 --build-arg ENV=dev .
    - name: listiii
      run: docker image list

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: excite13/shopfront
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: shopfront
