name: Maven build productcatalogue

on:
  push:
    branches:
      - master
    paths:
      - productcatalogue/**
  pull_request:
    branches:
      - master
    paths:
      - productcatalogue/**
  workflow_dispatch:

jobs:
  build_image:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: mvn -B package --file productcatalogue/pom.xml

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: excite13/productcatalogue
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: productcatalogue